---
# tasks file for cis-security

- name: Include OS base file name
  ansible.builtin.include_tasks: CIS-{{ ansible_distribution }}-{{ ansible_distribution_major_version | replace("Evaluation", "") }}.yml
