---
# tasks file for cis-security

- name: include appropriate type file
  ansible.builtin.include_tasks: CIS-{{ ansible_distribution }}-{{ ansible_distribution_major_version | replace("Evaluation", "") }}.yml
