---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image:  quay.io/swsmirror/amazonlinux:2
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
